# Generated by Django 4.1.7 on 2023-03-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_recipeingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='RecipeIngredients',
        ),
    ]
