# Generated by Django 4.1.7 on 2023-03-23 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0007_recipeingredients_uniqueingredientrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='Recipes.ingredient', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ингредиенты'),
        ),
    ]
