# Generated by Django 4.1.7 on 2023-03-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0009_alter_recipe_cooking_time_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='Recipes.recipe')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_by_tag', to='Recipes.tag')),
            ],
            options={
                'verbose_name': 'Тег в рецепте',
                'verbose_name_plural': 'Теги в рецептах',
            },
        ),
    ]
