# Generated by Django 4.1.7 on 2023-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0010_recipetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='Recipes.tag', verbose_name='Тэг'),
        ),
    ]
