# Generated by Django 4.1.7 on 2023-03-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0011_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=154, unique=True, verbose_name='Название'),
        ),
    ]
