# Generated by Django 4.1.7 on 2023-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0013_recipe_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
