# Generated by Django 4.1.7 on 2023-04-05 08:32

import Recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0014_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[Recipes.models.validate_color], verbose_name='Цвет'),
        ),
    ]
