# Generated by Django 4.1.7 on 2023-04-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0015_alter_tag_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTags',
        ),
    ]
