# Generated by Django 4.1.7 on 2023-04-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0013_recipe_created'),
        ('CapabilitiesUser', '0003_alter_favourites_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_shop_cart', to='Recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
