# Generated by Django 4.1.7 on 2023-03-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_alter_recipe_image'),
        ('CapabilitiesUser', '0003_alter_shoppingcart_author_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_fav', to='Recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
